puppetlabs/puppetlabs-release

Rakefile
configs/projects/puppetlabs-release-pc1.rb
ext/build_defaults.yaml
ext/project_data.yaml

In order to actually ship the release package, PC1 must be added to the
project config, and a build_defaults.yaml file is needed with PC1 set
for the apt and yum repo_name. A rakefile is also required to access
some of the packaging tasks not yet available via vanagon.

(RE-4059) Update puppetlabs-release-pc1 to enable shipping 

---

ext/build_defaults.yaml

Without this setting, packaging will look for a tarball when
uber_shipping, which will fail. This commit adds the setting so that
shipping can happen.

(RE-4059) Set build_tar to false in build_defaults

---

Gemfile
configs/projects/puppetlabs-release-pc1.rb

There is nothing architecture specific about this release package, it is
only vanagon that was limiting this ability. This commit adds the noarch
declaration to the project config and moves the gem dependency forward
to pick up the vanagon feature required to support this.

(RE-4375) Set noarch to true for the release package

---

Gemfile

This updates the version of vanagon to 0.3 providing additional platform support. 
Per @haus comments in #25

(maint) Bump vanagon version to 0.3

---

configs/components/repo_definition.rb
configs/projects/puppetlabs-release-pc1.rb
files/puppetlabs.list.txt

We are not shipping source packages yet for our puppet-agent releases.
As a result, running 'apt-get update' on a system where only
puppet-agent packages are available in the puppeltabs repo returns an
error. It's looking for the source repo, which isn't there. Since the
majority of new repos that we create do not yet have any sources, and
will not until puppetdb or puppetserver are shipped to them, we need to
deliver the repos with the source repo disabled.
If a user wants to access the source repos, all they have to do is
uncomment the line in the puppetlabs.list file provided by the release
package.

(maint) Comment out the source repo

---

ext/build_defaults.yaml

This data has been migrated to the build-data repo, to contend with
having to overwrite defaults set in the release team build-data settings

(maint) This was the wrong place to store this data

---

Gemfile
configs/components/gpg_key.rb
configs/components/repo_definition.rb
configs/projects/puppetlabs-release-pc1.rb
files/puppetlabs.repo.txt

Prior to this commit, we unintentionally had the puppetlabs-relelase-pc1
conflict with puppetlabs-release, which is causing heartburn for some
folks. This fix simply changes the filename for the GPG key once
installed to include a -PC1 suffix.
The behavior now mimics the behavior on Debian, as in both release
packages can be installed.

(CPR-210) Allow puppetlabs-release-pc1 to not conflict with original

---

README.md

Prior to this, we had no documentation for how to export a key for use
in the -release packages. This commit adds that information to the
README.

(RE-6080) Document GPG export commands for use by packages

---

Gemfile
README.md

Prior to this commit the user was unable to override the location and version of Vanagon.  This is the same behaviour we have in puppet-agent and pl-build-tools vanagon

(maint) Add VANAGON_LOCATION to pl-build-tools

---

Gemfile

Prior to this commit the user was unable to override the location and version of Vanagon.  This is the same behaviour we have in puppet-agent and pl-build-tools vanagon

(maint) Add VANAGON_LOCATION to PC1

---

configs/platforms/fedora-f23-i386.rb
configs/platforms/fedora-f23-x86_64.rb

This adds Fedora 23.  It requires Vanagon >= 0.5.0 + dada8190fa6bd05bc1b2719c4046ecc792e55dca  
Latest master is now installed by default :)

(RE-6253) Add Fedora 23 to release definitions for build tools

---

configs/platforms/fedora-f22-i386.rb
configs/platforms/fedora-f22-x86_64.rb
configs/platforms/fedora-f23-i386.rb
configs/platforms/fedora-f23-x86_64.rb

In the Fedora OSes that default to DNF, --best --allowerasing should be
there. If they are not, you can end up in situations where some packages
upgrade, but then dnf bails due to an impossible transaction.

(maint) Fix up DNF calls

---

Gemfile
configs/platforms/cisco-wrlinux-7-x86_64.rb
configs/platforms/ubuntu-15.10-amd64.rb
configs/platforms/ubuntu-15.10-i386.rb

As part of the puppet-agent 1.3.4 release Ubuntu 15.10 and cisco-wrlinux-7 were added.  This PR includes commits for both of those platforms, as well as enables the latest version of the packaging repo to be used for shipping.

New Platforms for puppet-agent 1.3.4

---

configs/components/repo_definition.rb

Note that for this platform, we are using jessie packages that
have been cross-compiled for powerpc.

(RE-6970) pl-build-tools repo package for huaweios

---

.rubocop.yml
Rakefile

This adds a `.rubocop.yaml` to the `master ` branch and fixes up the resulting Rubocop changes. Then it fixes the hostname and paths for shipping new puppetlabs-release packages.

(RE-6775) 2016 Spring Cleaning

---

Rakefile

Prior to this commit, this changes how the automation validates
signatures on our rpm packages. Previously, this was just checking the
return status of a command, but that was effectively always returning
true. This commit upates the check to ensrue the key we signed the
package with (or attempted to sign the package with) is actually present
and returned when we run `rpm -Kv`

(maint) Remove symlinking, fix sig check

---

configs/platforms/ubuntu-12.04-amd64.rb
configs/platforms/ubuntu-14.04-amd64.rb

The templates for Ubuntu 12.04 and 14.04 were updated and no longer include these packages by default.  They need to be explicitly defined.

(maint) Add rsync and fakeroot to Ubuntu 12.04 & 14.04

---

Rakefile
templates/redhat/puppetlabs-release.spec.erb
templates/redhat/puppetlabs.repo.erb

Prior to this commit, we were versioning the puppetlabs release packages
based on the platform version we were building them for. This was fine,
except it removed the ability to increment anything but the release
number. We are getting ready to make a large change to this package, but
in order to best to that, we should be able to increment the major or
minor version of the package. Unfortunately, due to the previous
versioning convention, we have to just increment the major version so
all the packages use the same one. Go us!

(maint) Set all release packages to same version

---

Rakefile

The check command doesn't exist, and when you try to run the rpm:ship
task, it fails. I assume this was a refactoring typo.

(maint) Remove check task for build_environment

---

Rakefile

The ship assumes that the path to the package contains 'rpm'. This isn't
how it is. This commit adds the rpm directory to the path as the ship
expects, because that's the easiest thing to do.

(maint) Fix path structure assumptions

---

Rakefile
templates/redhat/puppetlabs-release.spec.erb
templates/redhat/puppetlabs.repo.erb

This fixes a major issue with our release packages. There's a dependency
on redhat-release that's based on the platform version. However, when we
changed the platform version to not be the package version, this broke
that logic. This commit hopefully fixes it.

(maint) Fix major typo

---

configs/components/gpg_key.rb
configs/projects/puppetlabs-release-pc1.rb

Users in some cases need to install both the PC1 and "old school"
release packages on the same machine. The only issue is with conflicts
because both packages install the same keys. This is fine to have
duplicate keys installed, but rpm bails out when the files have the same
name. That's why we had to add the PC1 suffix to the puppet and
puppetlabs keys. We forgot to do the same for the nightly key. This
commit fixes that.

(maint) Add PC1 suffix to nightly key

---

configs/components/gpg_key.rb
configs/components/repo_definition.rb
configs/platforms/sles-11-x86_64.rb
configs/platforms/sles-12-x86_64.rb

We recently added sles repos to yum.puppetlabs.com. In order to keep the
workflow for these new repos consistent with other rpm based platforms,
we need to provide release packages for these repos. However, because
sles and zypper like to make things interesting, there are a few tweaks
we need to make to these packages. Yay sles!
Signed-off-by: Melissa Stone <melissa@puppet.com>

(RE-7959) Provide sles release packages

---

configs/components/gpg_key.rb
configs/components/repo_definition.rb
configs/projects/puppetlabs-release-pc1.rb

Prior to this commit, I was having issues installing the puppet release
packages on sles 11. The issue wasn't preventing the installation of
the packages, but it looks bad and it takes a long time to complete. It
only happens when we try to import the gpg keys during the postinstall
on sles 11.
```
warning: waiting for exclusive lock on /var/lib/rpm/Packages
error: cannot get exclusive lock on /var/lib/rpm/Packages
error: cannot open Packages index using db3 - Operation not permitted (1)
error: cannot open Packages database in /var/lib/rpm
error: /etc/pki/rpm-gpg/RPM-GPG-KEY-puppet-PC1: import failed.
```
Importing the keys was only a means to keep the sles release packages
in line with other platform release packages. When the keys are not
installed, the user must manually import them to …

(maint) Only attempt to import the keys on sles 12

---

configs/components/gpg_key.rb
configs/projects/puppetlabs-release-pc1.rb

So sles doesn't automatically import gpg keys when you use a repo for
the first time. To fix this, I included a postinst script to manually
import the keys for the user. This worked when I tested on sles 12, but
not on sles 11. It turns out the version of rpm on sles 11 isn't smart
enough to be able to call rpm within rpm, so it couldn't handle it. Sles
12 seemed to be smarter and able to handle this situation. However, it
seems some users are on older, less-updated versions of sles 12 and are
running into the issue we had seen on sles 11.
I give up, ya'll can just manually import the gpg keys yourselves.

(CPR-383) Remove gpg key import on sles

---

configs/projects/puppetlabs-release-pc1.rb

This will let us pick up new `%pre` & `%post` requirements from Vanagon.
(This will require a Vanagon release that includes commit [61d5d36a](https://github.com/puppetlabs/vanagon/commit/61d5d36ae006e16e95cb56a406479e129f1397f9))

(CPR-393) Bump release

---

Gemfile

Pinning to Vanagon 0.9.1 or newer will allow us to rebuild `puppetlabs-release` RPMs with the [upstream RPM dependency fix](https://github.com/puppetlabs/vanagon/commit/61d5d36ae006e16e95cb56a406479e129f1397f9).
`Gemfile` just gotten jostled around a bit because some of it was out of date and this was a safe place to poke around without disturbing more active repos. The `vanagon_location_for` function will hopefully be refactored right out soon, but until then it should at least be kept up to date and well structured.

Update Gemfile & pin to newer Vanagon release

---

configs/components/repo_definition.rb
configs/platforms/ubuntu-16.10-amd64.rb
files/puppetlabs-puppet-agent-pin-1000.txt

Ubuntu 16.10 shipped with a puppet-agent package that was versioned based on the included version of puppet (4.5.2). This means the distro package would override Puppet Inc's puppet-agent AIO package version (1.x). We are working around this by pinning our puppet-agent package to a higher priority in an apt preferences config file.
I've tested this by creating a simple apt repository on a vmpooler host and modifying the urls to point to that instead of apt.puppetlabs.com. If the distro puppet-agent package hasn't been installed yet, this does the right thing and installs our AIO puppet-agent package. :+1: 
However, if the distro puppet-agent package has already been installed, an apt-get upgrade doesn't seem to upgrade the package to our AIO version. I had to raise the Pin-Priority of our …

Add Ubuntu 16.10 platform with package pinning enabled for puppet-agent

---

Gemfile

We need at least vanagon 0.9.3 in order to specify platform `dist`s.

(maint) Update to use at least vanagon 0.9.3

---

configs/projects/puppet5-nightly-release.rb

We want to make sure people are either using the individual numbered
repos (i.e., puppet5, puppet6, etc.) or they're using the rolling
symlinked repos. Not both.

(maint) Add conflicts on puppet-release and puppet-nightly-release

---

configs/platforms/fedora-f24-x86_64.rb

This commit removes the platform config for fedora 24.

(RE-9690) Remove EOL platform definitions

---

configs/projects/puppet5-nightly-release.rb
files/puppet5-nightly.list.txt

This commit adjusts the apt repo url to point to the apt directory on nightlies. Before, the nightlies base url was being treated as the apt url and files were not being found correctly.

(maint) Fix apt repo url

---

configs/platforms/fedora-f26-x86_64.rb

This commit duplicates the fedora-26-x86_64 config to have an f-prefixed version. This will allow us to have working release packages for fedora until CPR-391 and friends get resolved.

(maint) Add repo config for fedora-f26-x86_64

---

ext/build_defaults.yaml

This commit removes the repo_link_target param from build_defaults. Since we have started shipping things to puppet6-nightly repos, we don't want shipping puppet5-nightly artifacts to overwrite the link from puppet6-nightly to puppet-nightly.

(maint) Remove repo_link_target

---

configs/platforms/ubuntu-18.04-amd64.rb

Here's a platform definition to add Ubuntu 18.04 - if this looks alright, I can open PRs for the other branches as well (puppet5-nightly, puppet6, and puppet6-nightly, right?)

(BUILD-148) Add support for Ubuntu 18.04

---

ext/build_defaults.yaml

This commit changes the packaging branch to 1.0.x, which has many improvements
to our shipping automation. This repo is not quite set up to use packaging as a
gem yet.

(maint) Use packaging#1.0.x

---

configs/platforms/ubuntu-18.04-amd64.rb

Copied from the existing config on the puppet5 branch.

(CPR-581) Add nightly support for Ubuntu-18.04 (bionic)

---

configs/platforms/fedora-28-x86_64.rb

Copied the fedora-27-x86_64 config.

(PA-1862) Add support for fedora-28-x86_64

---

.gitignore
Gemfile
Rakefile

This commit updates the `vanagon_location_for` method to be more generic and
makes use of it (now `location_for`) when setting the packaging dependency.

(maint) Use packaging as a gem

---

Gemfile

This commit updates the `vanagon_location_for` method to be more generic and
makes use of this new `location_for` method to set gem versions for vanagon and
packaging. This commit also updates these dependencies to be loosely pinned so
that new non-major gem versions will automatically get pulled in.

(maint) Update vanagon and packaging dependencies

---

configs/platforms/el-8-x86_64.rb

This commit adds a platform config for el-8-x86_64. This config was copied from
the existing el-7-x86_64 config. The only changes were changing 7 to 8 and
changing the `vmpooler_template` to redhat instead of centos, since there is no
centos-8-x86_64 vm right now.

(CPR-649) Add support for el-8-x86_64

---

files/README-apt.txt
files/README-downloads.txt
files/README-yum.txt

First commit is what's currently on yum/apt/downloads.
Second commit makes changes.
There are also a handful of additional READMEs on downloads.puppet.com that I didn't copy over to here. Not sure if we want to keep those or not.

(RE-12316) Update READMEs

---

files/README-apt.txt
files/README-downloads.txt
files/README-nightlies-apt.txt
files/README-nightlies-downloads.txt
files/README-nightlies-yum.txt
files/README-nightlies.txt
files/README-yum.txt

This commit adds READMEs for the top level of nightlies.puppet.com as well as
the yum, apt, and downloads subdirectories.

(RE-12316) Add READMEs for nightlies

---

files/puppet-nightly.list.txt
files/puppet-nightly.repo.txt
files/puppet.list.txt
files/puppet.repo.txt
files/puppet5-nightly.list.txt
files/puppet5-nightly.repo.txt
files/puppet6-nightly.list.txt
files/puppet6-nightly.repo.txt
files/puppet6.list.txt
files/puppet6.repo.txt

This commit removes the yum source repositories from the puppet5-nightly,
puppet6-nightly, puppet-nightly, puppet6, and puppet repo configs. We have not
made source packages available in these repos, so there's no need for them in
the configs.

(CPR-658) Remove source repositories

---

configs/projects/puppet-tools-release.rb
files/puppet-enterprise-tools.list.txt
files/puppet-enterprise-tools.repo.txt
files/puppet-tools.list.txt
files/puppet-tools.repo.txt

This commit renames the puppet-enterprise-tools package repository to
puppet-tools. This allows us to point both FOSS and PE users to the same set
of installation instructions for non-Puppet-Platform products like Bolt.

(RE-12521) Rename puppet-enterprise-tools repo to puppet-tools

---

configs/components/repo_definition.rb
configs/projects/puppet-archives-release.rb
configs/projects/puppetlabs-release-pc1.rb

On SLES, there must be an '=' before the file:/// URL for gpgkey.
However, there can only be one, otherwise zypper is unhappy.
This change will prepend a '=' to the gpgkey 'file:///' path
on SLES but only if one does not yet exist.
I tested the sed logic locally but not sure what other testing we
do (or if there's any other file updates needed) to verify.

(RE-12490) Fix SLES gpgkey handling

---

configs/projects/puppet-tools-release.rb

puppet-tools-release should be installable alongside puppet*-release
packages.

(CPR-717) Remove unnecessary conflicts from puppet-tools-release

---

configs/platforms/cisco-wrlinux-5-x86_64.rb
configs/platforms/cisco-wrlinux-7-x86_64.rb
configs/platforms/el-5-x86_64.rb
configs/platforms/el-6-x86_64.rb
configs/platforms/el-7-x86_64.rb
files/README-apt.txt
files/README-downloads.txt
files/README-nightlies-apt.txt
files/README-nightlies-downloads.txt
files/README-nightlies-yum.txt
files/README-yum.txt
files/puppet-nightly.list.txt
files/puppet-nightly.repo.txt
files/puppet-tools.list.txt
files/puppet-tools.repo.txt
files/puppet.list.txt
files/puppet.repo.txt
files/puppet5-nightly.list.txt
files/puppet5-nightly.repo.txt
files/puppet5.list.txt
files/puppet5.repo.txt
files/puppet6-nightly.list.txt
files/puppet6-nightly.repo.txt
files/puppet6.list.txt
files/puppet6.repo.txt

Find cases inside our release packages and documentation that use
'http:'; switch them to use 'https:'
Test each one by grepping each of the URLs and verifying that
they resolve.

(CPR-517) Use https as much as possible

---

configs/projects/puppet5-release.rb
files/puppet5.repo.txt

i think at some point this file was copied over incorrectly to include nightly
which was causing the source rpm to point to the wrong thing

(CPR-736) fix puppet5.repo file to not include "nightly"

---

README.md
Rakefile

The README referred to a non-existent branch, which I removed.
Also, made reference to the confluence page with how-to instructions.
Ideally, the confluence doc should move into the README, but that's for another time.

The Rakefile still had 'implode' warning. This is no longer needed.

---

configs/components/repo_definition.rb
configs/projects/puppet5-release.rb
configs/projects/puppet6-release.rb
files/puppet5.repo.txt
files/puppet6.repo.txt

Yum packages allow for multiple GPG signing keys. Keep the old one
during the transition but add in the new one for future use.

(RE-13419) Add new key as secondary line for yum packages

---

files/puppet-nightly.sles.txt
files/puppet5-nightly.sles.txt
files/puppet6-nightly.sles.txt
files/puppet7-nightly.sles.txt

The config files for sles where pointing to
puppet-nightly.list.txt which configure deb definitions.
Updated the symlinks to puppet-nightly.repo.txt
which contain rpm definitions.
This is causing the following error:
```
❯ zypper install puppet-agent
Unexpected exception.
/etc/zypp/repos.d/puppet7-nightly.repo: Section []: Line 2 contains garbage (no '=' or ',|/\' in key)
Please file a bug report about this.
See http://en.opensuse.org/Zypper/Troubleshooting for instructions.
❯ cat /etc/zypp/repos.d/puppet7-nightly.repo
deb http://nightlies.puppet.com/apt __CODENAME__ puppet7-nightly
```

(maint) update puppet-nightly.sles.txt files

---

configs/platforms/el-8-aarch64.rb
configs/projects/puppet-nightly-release.rb
configs/projects/puppet-release.rb
configs/projects/puppet6-nightly-release.rb
configs/projects/puppet6-release.rb
configs/projects/puppet7-nightly-release.rb

This PR adds support for Rhel 8 aarch64 on Puppet 6 and Puppet 7.

(CPR-758) Build puppet-release for RedHat 8 aarch64

---

configs/projects/puppet-release.rb
configs/projects/puppet5-release.rb
configs/projects/puppet7-release.rb
files/puppet7.list.txt
files/puppet7.repo.txt
files/puppet7.sles.txt

Let me know if I missed anything. Aside from this, there's also the issue of symlinking `puppet7-release` to `puppet-release`, which should be done somewhere in packaging? I'm not sure.

(maint) Add puppet7 release packages

---

configs/projects/puppet-tools-release.rb
files/puppet-tools.sles.txt

Bolt uses the puppet-tools release packages. Need to keep them
up-to-date. This got left behind when we broke out SLES for GPG
key update considerations.

(RE-13823) Add SLES component to puppet-tools release

---

configs/projects/puppet-nightly-release.rb
configs/projects/puppet5-nightly-release.rb
configs/projects/puppet6-nightly-release.rb
configs/projects/puppet7-nightly-release.rb
files/puppet-nightly.repo.txt
files/puppet-nightly.sles.txt
files/puppet5-nightly.repo.txt
files/puppet5-nightly.sles.txt
files/puppet6-nightly.repo.txt
files/puppet6-nightly.sles.txt
files/puppet7-nightly.repo.txt
files/puppet7-nightly.sles.txt

I neglected the nightly release packages when I updated the release
packages with the new key. This commit fixes that problem.
While puppet5 may be EOL, I'm including it for the sake of consistency
and paranoia.

(RE-13419) Update nightly release packages with new key

---

configs/projects/puppet-nightly-release.rb
configs/projects/puppet-release.rb
configs/projects/puppet7-nightly-release.rb
configs/projects/puppet7-release.rb

Left the 'floating' puppet version to only conflict with the puppet7-release.
Automatic replacement would cause issues durint 'floating' transition from one puppet
version to the next.

(CPR-762) Add 'replaces' for older puppet versions

---

configs/platforms/ubuntu-22.04-amd64.rb
configs/projects/puppet-nightly-release.rb
configs/projects/puppet-release.rb
configs/projects/puppet6-nightly-release.rb
configs/projects/puppet6-release.rb
configs/projects/puppet7-nightly-release.rb
configs/projects/puppet7-release.rb

I've been installing the `focal` release for my testing and would like to see some support. At the very least, with the `nightlies` release.

Add Ubuntu 22.04 support

---

configs/projects/puppet6-release.rb

puppet6-release-6.0.0-22.el8.noarch.rpm didn't make it correctly through
CI, re-release with version incremented.

(CPR-867) Increment the release version for puppet6 and rebuild

---

ci/create-packages

We were inserting an incorrect '.' in the version string metadata

(maint) fix deb packaging metadata

---

source/projects/puppet-nightly-release.json
source/projects/puppet-release.json
source/projects/puppet-tools-release.json
source/projects/puppet7-nightly-release.json
source/projects/puppet7-release.json
source/projects/puppet8-nightly-release.json
source/projects/puppet8-release.json

Amazon 7 is an implementation detail, the actual OS is named Amazon 2
~Blocked on release of packaging gem with this change https://github.com/puppetlabs/packaging/pull/1259~

Rename Amazon 7 to 2

---

ci/create-packages

Tested (with additional testing for puppet7 -> puppet8 upgrade and puppet -> puppet8 upgrade) all successful.
```
root@unmixed-ballot:~# dpkg  -i puppet7-release_7.0.0-20noble_all.deb
Selecting previously unselected package puppet7-release.
(Reading database ... 83309 files and directories currently installed.)
Preparing to unpack puppet7-release_7.0.0-20noble_all.deb ...
Unpacking puppet7-release (7.0.0-20noble) ...
Setting up puppet7-release (7.0.0-20noble) ...
root@unmixed-ballot:~# dpkg  -i puppet-tools-release_1.0.0-17noble_all.deb
Selecting previously unselected package puppet-tools-release.
(Reading database ... 83314 files and directories currently installed.)
Preparing to unpack puppet-tools-release_1.0.0-17noble_all.deb ...
Unpacking puppet-tools-release (1.0.0-17noble) ... …
```

RE-16360: Don't install preferences file with puppet-tools-release

---

ci/create-packages
source/apt.puppet.com/puppet-release.list.template
source/apt.puppet.com/puppet-tools-release.list.template
source/apt.puppet.com/puppet7-release.list.template
source/apt.puppet.com/puppet8-release.list.template
source/nightlies.puppet.com/puppet-nightly-release.list.template
source/nightlies.puppet.com/puppet7-nightly-release.list.template
source/nightlies.puppet.com/puppet8-nightly-release.list.template

In this PR, I'm trying to follow the recommendations from https://wiki.debian.org/DebianRepository/UseThirdParty to move away from trusted.d and use signed-by option with keyrings.
This should solve some error encountered when using puppetlabs-puppet module since the merge of https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/681 (eg. https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/681#issuecomment-2204502810) 
I was still not sure if in the case of puppetlabs-release we should rather put the keyring in `/etc/apt/keyrings` or `/usr/share/keyrings`, feel free to correct me if needed.

use apt keyring instead of trusted.d
