- configs/components/repo_definition.rb
- configs/platforms/nxos-5-x86_64.rb
Tested by successfully building the release rpm package for nxos.
> (RE-4881) Add nxos platform support

- configs/components/repo_definition.rb
- configs/platforms/cisco-wrlinux-5-x86_64.rb
This supports the re-naming of nxos to cisco-wrlinux
> (RE-5373) Initial config for cisco-wrlinux-5-x86_64

- configs/platforms/ubuntu-15.10-amd64.rb
- configs/platforms/ubuntu-15.10-i386.rb
Adds Ubuntu 15.10 Wily to build-tools.
> (RE-5475) Add Ubuntu 15.10 to release definitions for build tools

- configs/platforms/huaweios-6-powerpc.rb
Tested by building a repo package and inspecting it - looks sane to me.
> (RE-6785) Add huaweios platform

- configs/platforms/fedora-f24-x86_64.rb
Adds Fedora 24 release package to pl-build-tools
> (RE-7332) Add Fedora 24 to release definitions for build tools

- configs/platforms/fedora-f25-x86_64.rb
- configs/platforms/ubuntu-16.10-amd64.rb
Add platform configs for release package generation on pl-build-tools.
> Add Fedora 25 and Ubuntu 16.10 platforms

- configs/projects/puppet6-nightly-release.rb
I'm shipping new, non-f fedora release packages.
> (maint) Bump the release

- .gitignore
- configs/projects/puppet-enterprise-tools-release.rb
- files/puppet-enterprise-tools.list.txt
- files/puppet-enterprise-tools.repo.txt
see individual commit messages for details
> (RE-12370) Add puppet-enterprise-tools release package

- configs/components/archive_repo_definition.rb
- configs/projects/puppet-archives-release.rb
The same as https://github.com/puppetlabs/puppetlabs-release/pull/191
but this time include puppet-archives-release.
> (RE-12490) Fix SLES gpgkey handling

- configs/platforms/fedora-31-x86_64.rb
copied template from fedora 30
> (CPR-720) Add support for Fedora 31

- configs/projects/puppet-nightly-release.rb
- configs/projects/puppet-release.rb
- configs/projects/puppet-tools-release.rb
- configs/projects/puppet5-nightly-release.rb
- configs/projects/puppet5-release.rb
- configs/projects/puppet6-nightly-release.rb
- configs/projects/puppet6-release.rb
- files/README-apt.txt
- files/README-nightlies-apt.txt
- files/puppet-nightly.list.txt
- files/puppet-tools.list.txt
- files/puppet.list.txt
- files/puppet5-nightly.list.txt
- files/puppet5.list.txt
- files/puppet6-nightly.list.txt
- files/puppet6.list.txt
It felt painful to do a full revert. I'm hoping we can just revert debian.
> (CPR-517) Partial revert of CPR-517 to deal with debian breakage.

- configs/platforms/ubuntu-20.04-amd64.rb
- configs/projects/puppet-nightly-release.rb
- configs/projects/puppet-release.rb
- configs/projects/puppet6-nightly-release.rb
- configs/projects/puppet6-release.rb
> (PA-3136) Add ubuntu-20.04 focal

- configs/projects/puppet5-nightly-release.rb
- configs/projects/puppet6-nightly-release.rb
- configs/projects/puppet7-nightly-release.rb
- files/puppet7-nightly.list.txt
- files/puppet7-nightly.repo.txt
https://artifactory.delivery.puppetlabs.net/artifactory/scratchpad__local/puppet7-nightly-release-1.0.0-1.el8.noarch.rpm
https://artifactory.delivery.puppetlabs.net/artifactory/scratchpad__local/puppet7-nightly-release_1.0.0-1bionic_all.deb
```
warning: /var/cache/dnf/puppet7-nightly-a08362f4cd5b9a25/packages/puppet-agent-7.0.0.68.g0d7046fb-1.el8.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID ef8d349f: NOKEY
Puppet 7 Nightly Repository el 8 - x86_64                                                                              1.6 MB/s | 1.6 kB     00:00
Importing GPG key 0xEF8D349F:
Userid     : "Puppet, Inc. Release Key (Puppet, Inc. Release Key) <release@puppet.com>"
Fingerprint: 6F6B 1550 9CF8 E59E 6E46 9F32 7F43 8280 EF8D 349F
From       : …
```
> (CPR-756) Add puppet7 nightly release packages

- files/puppet7-nightly.sles.txt
sles builds are failing without it
ran sles-12 and sles-15 build & it succeeded
> (maint) Add puppet7-nightly.sles.txt file

- files/puppet-nightly.sles.txt
- files/puppet5-nightly.sles.txt
- files/puppet6-nightly.sles.txt
previously only added for puppet7, all vers need it
since we already know this works for 7 i'm gonna merge it myself (and I tested a build with each one)
> (maint) Add puppet-nightly.sles.txt files for all puppet versions

- configs/platforms/fedora-32-x86_64.rb
- configs/projects/puppet-nightly-release.rb
- configs/projects/puppet-release.rb
- configs/projects/puppet6-nightly-release.rb
- configs/projects/puppet6-release.rb
> (PA-3219) Add support for fedora 32

- configs/projects/puppet-nightly-release.rb
- configs/projects/puppet-release.rb
- configs/projects/puppet-tools-release.rb
- configs/projects/puppet5-nightly-release.rb
- configs/projects/puppet5-release.rb
- configs/projects/puppet6-nightly-release.rb
- configs/projects/puppet6-release.rb
- configs/projects/puppet7-nightly-release.rb
- configs/projects/puppet7-release.rb
- files/README-repo-sles.txt
- files/puppet-tools.sles.txt
- files/puppet.sles.txt
- files/puppet5.sles.txt
- files/puppet6.sles.txt
- files/puppet7.sles.txt
SLES release packages do not allow multiple keys. Now is the
switchover time to the new key.
> (maint) switch SLES release packages over to new GPG key

- configs/components/gpg_key.rb
- configs/components/repo_definition.rb
- configs/platforms/el-5-x86_64.rb
- configs/platforms/el-6-x86_64.rb
- configs/platforms/el-7-x86_64.rb
- ext/build_defaults.yaml
- files/pl-build-tools.repo.txt
Also, fix up the gpg munging effort for SLES. It's still kindof terrible but
at least it's a little bit more readable, I hope
> (maint) Add 2025 gpg for el

- source/projects/puppet-nightly-release.json
- source/projects/puppet-release.json
- source/projects/puppet-tools-release.json
- source/projects/puppet7-nightly-release.json
- source/projects/puppet7-release.json
- source/projects/puppet8-nightly-release.json
- source/projects/puppet8-release.json
> (PA-6271) Build and ship puppet nightly release packages for Amazon Linux2

- source/projects/puppet-tools-release.json
Remove the preference file from puppet-tools-release
> (RE-16379) Prep for puppet-tools-release 1.0.0-18
